name: mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.22.0
      - cloudpickle==3.1.1
      - numpy==1.26.4
      - pandas==2.1.4
      - psutil==5.9.8
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - typing-extensions==4.10.0
      - plotly==5.21.0  # ✅ Versi stabil terbaru yang cocok untuk Python 3.10
